# In this class, you will learn to use Python!
Helpful online reference for Python 
  * https://docs.python.org/3/tutorial/introduction.html
  * https://docs.python.org/3/tutorial/controlflow.html
  
Optional extra learning material: An online course for Python 
  * https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/index.htm

In [2]:
#### These three lines should be in a cell at the top of any notebook
#### These lines load standard tools that will be usefull to us
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


# Understanding cell output
Use the `print()` function to output raw values stored in a variable

In [2]:
print('hello world')
print(10, 1.1321)
n = arange(3)
print(n)

hello world
10 1.1321
[0 1 2]


# How to get help within Jupyter

In [3]:
### Try uncommenting (delete the `#` symbol at the beginning of the line) any of these
help(arange)
#help(plot)
#help(zeros)
#help(linspace)

### You can also use `?` instead of `help()`
### Try uncommenting and running one of the following lines
#?plot
#?zeros
#?linspace

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

# Lesson 1
Every time you execute a cell (shift + return), the variables are saved into the workspace. If you push the reset button (circle with the arrow at the top or the 'Kernel' tab -> restart) the workspace is cleared. After restarting, you will have to run the top cell that loads the common modules. If you don't you will likely get an error. 

If you run a cell that depends on variables that were generated in a previous cell, then you might get an error if you execute them out of order.

In [4]:
## Lesson 1, cell A
x = 2.2
print(x)

2.2


In [5]:
## Lesson 1, cell B
y = x*5
print(y)

11.0


# Try restarting the notebook
  * Restart the notebook (circle with the arrow at the top or the 'Kernel' tab -> restart)
  * Execute Lesson 1, cell B. If you restarted the notebook successfully, you should get an error.
  * Now execute Lesson 1, cell A first. Do you get an error? Now do you get an error if you execute Execute 1, cell B?

# Some math
Most mathematical operations work as expected. For example
  * $xy$ = `x*y`
  * $x/y$ = `x/y`
  * $\ln(x)$ = `log(x)`

But some work differently
  * $x^2$ = `x**2`

In [4]:
x = 5.5
print('x^2 =', x**2)

x^2 = 30.25


# What happens if you try `x^2` instead of `x**2`?

In [10]:
x = 1.5
y = x^2
print('x^2 =', y)

TypeError: unsupported operand type(s) for ^: 'float' and 'int'

# Lesson 2: Arrays
Arrays are similar to mathematical vectors. Typically, it is a collection of numbers that can be accessed by an integer index. For example $x = [20, 4, 7]$ is an array with $x[0] = 20$, $x[1] = 4$, etc.

Accessing array elements is done using square brackets. If $j$ is an integer and $x$ is an array then $v[j]$ is the jth element of the array.

There are three types of arrays that are useful for us. Examples of each are included in the following cells.
  1. **Lists:** A list is very simple and adaptable. You don't need to know how large a list will be (i.e., how  many elements it will have) before you create one. However, you cannot do mathematical operations on a list
  2. **Numpy array:** You must know how many elements this type of array will have when you create it. The benifit is that you can do mathematical operations to it. By default mathematical operations are applied to each element individually.
  3. **Numpy matrix:** Almost identical to a Numpy array, except that mathematical operations follow the linear algebra definitions by default

In [6]:
### Lists
a_list = [6, 22, 4]
print(a_list)
another_list = [9, -5.1, 0]
print(another_list)

[6, 22, 4]
[9, -5.1, 0]


In [7]:
a_list*another_list

TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
a_npArray = array([6, 22, 4])
print(a_npArray)
another_npArray = array([9, -5.1, 0])
print(another_npArray)
y = a_npArray*another_npArray
print(y)

[ 6 22  4]
[ 9.  -5.1  0. ]
[  54.  -112.2    0. ]


In [19]:
a_npMatrix = matrix([6, 22, 4])
print(a_npMatrix)
print('Transpose of a matrix (also works for arrays)')
print(a_npMatrix.T)
print('elementwise is the default for Numpy arrays')
print(a_npArray*a_npArray.T)
print('linear algebra is the default for Numpy matrices')
print(a_npMatrix*a_npMatrix.T)

[[ 6 22  4]]
Transpose of a matrix (also works for arrays)
[[ 6]
 [22]
 [ 4]]
elementwise is the default for Numpy arrays
[ 36 484  16]
linear algebra is the default for Numpy matrices
[[536]]
